# Generated by Django 6.0.5 on 2026-05-23 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance_km',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Distancia de la ruta en kilómetros (calculado por OSRM)', max_digits=8),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duración estimada del viaje en minutos (calculado por OSRM)'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['price_per_seat'], name='trips_trip_price_p_4eb671_idx'),
        ),
    ]
