# Generated by Django 6.0.5 on 2026-05-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_distance_km_trip_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de asientos reservados en esta transacción'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
